// generated by "sampctl init"
#include <open.mp>
#include <YSI_Storage\y_ini>
#include <YSI_Coding\y_hooks>
#include <Pawn.CMD>
#include <sscanf2>

#include "includes/config/defines.pwn"
#include "includes/config/dialogs.pwn"
#include "includes/config/colors.pwn"
#include "includes/core/server.pwn"

#include "includes/auth/auth_data.pwn"
#include "includes/auth/auth_io.pwn"
#include "includes/auth/auth_utils.pwn"
#include "includes/auth/auth_dialogs.pwn"
#include "includes/auth/auth.pwn"

#include "includes/admin/admin_data.pwn"
#include "includes/admin/admin_utils.pwn"
#include "includes/admin/admin_dialogs.pwn"
#include "includes/admin/admin.pwn"
#include "includes/admin/admin_cmds.pwn"

#include "includes/rol/rol_data.pwn"
#include "includes/rol/rol_utils.pwn"
#include "includes/rol/rol_dialogs.pwn"
#include "includes/rol/rol.pwn"
#include "includes/rol/rol_cmds.pwn"

#include "includes/core/callbacks.pwn"

main()
{
	// write code here and run "sampctl build" to compile
	// then run "sampctl run" to run it
}
