// generated by "sampctl init"
#include <open.mp>
#include <YSI_Storage\y_ini>
#include <YSI_Coding\y_hooks>

#include "includes/core/define.pwn"
#include "includes/core/main.pwn"

#include "includes/auth/auth_data.pwn"
#include "includes/auth/auth_io.pwn"
#include "includes/auth/auth_dialogs.pwn"
#include "includes/auth/auth.pwn"


main()
{
	// write code here and run "sampctl build" to compile
	// then run "sampctl run" to run it
}
